server:
  port: 8069
spring:
#  application:
#    name: rmc-user
  datasource:
    url: jdbc:mysql://mysql:3306/zg_mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
#    password: 1qaz@WSX
    password: root
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
      host: redis # Redis服务器地址
      database: 1 # Redis数据库索引（默认为0）
      port: 6379 # Redis服务器连接端口
      password: zkc654321 # Redis服务器连接密码（默认为空）
      timeout: 3000ms # 连接超时时间（毫秒）
mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
  # 关闭mybatisplus启动图标
    banner: off
    db-config:
      # 全局默认主键类型
      id-type: AUTO
      # 表名、是否使用下划线命名，默认数据库表使用下划线命名
      table-underline: true
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0
  mapper-locations:
  - /mapper/*.xml
management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always