server:
  port: 9000
spring:
  application:
    name: rmc-user

  datasource:
    url: jdbc:mysql://localhost:3306/zg_rmc?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always