server:
  port: 8201
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true #使用小写service-id
      routes: #配置路由路径
        - id: rmc-user #路由唯一标识，路由到rmc-user
          uri: lb://rmc-user  # 需要转发的地址服务名，使用了nacos 服务注册名称 lb使用nacos本地负载均衡策略
           #断言规则，用于路由规则匹配
          predicates:
            - Path=/rmc_user_service/**
            # 转发之前去掉第一层路径
          filters:
            - StripPrefix=1
        - id: rmc-auth
          uri: lb://rmc-auth #需要转发的地址
          predicates:
            - Path=/rmc-auth/**
          filters:
            - StripPrefix=1
        - id: rmc-monitor-management
          uri: lb://rmc-monitor-management
          predicates:
            - Path=/rmc-monitor-management/**
          filters:
            - StripPrefix=1
#配置RSA的公钥访问地址
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:8201/rmc-auth/rsa/publicKey'
redis:
    database: 1
    port: 6379
    host: 47.101.31.117
    password: zkc654321
    lettuce:
          pool:
            max-active: 8
            max-wait: -1ms
            max-idle: 8
            min-idle: 0
secure:
  ignore:
    urls: #配置白名单路径
      - "/doc.html"
      - "/swagger-resources/**"
      - "/swagger/**"
#      - "/swagger-ui.html"
      - "/*/v2/api-docs"
      - "/*/*.js"
      - "/*/*.css"
      - "/*/*.png"
      - "/*/*.ico"
      - "/webjars/**"
      - "/actuator/**"
      - "/rmc-auth/oauth/token"
      - "/rmc-user/resource/initResourceRolesMap"
      - "/rmc-auth/rsa/publicKey"
      - "/rmc-auth/login"
      - "/rmc-user/admin/login"
      #- "/rmc-user/admin/*"
      - "/rmc-auth/oauth/authorize"
      - "/rmc-auth/oauth/token"
management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always